### ISSUE TITLE
worthy of continued attention

### ISSUE THREAD

**Issue by ihorizons2022** [MrNeRF/gaussian-splatting-cuda#2]

**Comment by ihorizons2022** [comment]
personally, having several questions about 3DGS
1. could use other viewers, maybe blender to render the result.
2. comparing with INGP, what is your opinion which is more promising
3. could the output fit to the current gaming or 3d reconstruction pipelines, for example, exporting mesh obj

**Comment by MrNeRF** [comment]
Hi [ihorizons2022](https://github.com/ihorizons2022),

Thank you for raising these points. While they might be more suited for the discussion section than an issue, I'll do my best to address them given the current information.

1. **Other Viewers**: I'm indeed considering the addition of a built-in viewer. However, at the moment, I'm uncertain about integrating it with Blender.
  
2. **Comparison with instant-ngp**: 3DGS and instant-ngp adopt divergent approaches. While instant-ngp leverages neural networks and its unique hash encoding, 3DGS functions as a rasterizer, featuring both differential and optimization components. Quality-wise, 3DGS stands out, but when it comes to speed, they're relatively comparable, especially considering the optimized implementation of instant-ngp with its tiny-nn version. That said, a primary objective of this project is to enhance 3DGS's speed, aiming to render it almost instantaneous. It remains to be seen if we'll achieve this.
   
   Furthermore, there are notable distinctions between the two: For instance, the output of instant-ngp (in terms of neural network weights) can be stored more compactly than 3DGS's output. I anticipate further differences, and I'm committed to deepening my understanding in the coming weeks.

3. **Utilizing Neuroangelo**: I don't claim expertise in this area, but I'm hopeful about leveraging Neuroangelo in some capacity. Presently, my insights into it remain limited, but rest assured, it's on my to-do list.

I hope this provides some clarity. I'll keep this issue active for one more day before closing. Should you wish to delve deeper, please initiate a discussion.

**Comment by ihorizons2022** [comment]
thanks.

for speed, 3DGS is actually 3x - 5x slower than INGP in practice.
looking forward to your progress
