### ISSUE TITLE
[Feature] Load config params from yaml file

### ISSUE THREAD

**Issue by DapengFeng** [MrNeRF/gaussian-splatting-cuda#35]

**Comment by MrNeRF** [comment]
This has been for a while on my todo list. I think I will do it today however, but it won't be json. Instead I'll use json since I already have this dependency.

**Comment by MrNeRF** [comment]
Already done!
https://github.com/MrNeRF/gaussian-splatting-cuda/commit/8ac4f69bf451b36a63393e05c27f3261019469a0
