### ISSUE TITLE
Minor issues...

### ISSUE THREAD

**Issue by MikePelton** [MrNeRF/gaussian-splatting-cuda#38]
Hi - thanks for this code - it's excellent and runs on an RTX A6000 you'll be pleased to hear. During the build I had a couple of issues, one being that Torch_DIR needed to be defined for cmake to find it, and also that tbb needed to be installed - neither issue exactly life-threatening!

**Comment by MrNeRF** [comment]
Hi @MikePelton,
thx. This morning I removed tbb as dependency. I don't know when you cloned, but it should no longer be an issue with the latest commit. 

If you unpack torch to external/libtorch, it should be found automatically (as described in the Readme). Had no bug reports regarding libtorch. But what exactly was the error?

Anyway, glad you like it and nice that it works on your gpu :)

**Comment by MikePelton** [comment]
Tracking back, I had a fat finger moment and unpacked torch into the wrong folder, hence cmake not finding it where it expected. Just in case anyone else does the same thing it's easily fixed by explicitly setting Torch_DIR e.g.:
export Torch_DIR=/sharedVolume/gaussian-splatting-cuda/libtorch/share/cmake/Torch
...then running cmake again.
