### ISSUE TITLE
About the acceleration compared with official pytorch implementation

### ISSUE THREAD

**Issue by vairleon** [MrNeRF/gaussian-splatting-cuda#59]
I was wondering what the mainly differences are between your C++ implementation and original pytorch implementation, since both are based on the Torch backend. Could u introduced a bit about which specific part you accelerated to achieve a performance improvement of 30% over the original pytorch implementation?

**Comment by MrNeRF** [comment]
Hey,
it was mostly done in the backward pass where the gradients are computed by better utilizing shared memory.

Anyway, since this June or so this is nowhere near state of the art. I am working slowly towards migrating to gsplat also to get rid of this annoying INRIA license.
