### ISSUE TITLE
Killed, when creating scene with more than 2500 Mpixel total

### ISSUE THREAD

**Issue by aml2007** [MrNeRF/gaussian-splatting-cuda#65]
I managed to build and run on Ubuntu 24.04 with Cuda 12 (thanks to https://github.com/graphdeco-inria/gaussian-splatting/issues/923#issue-2447623144), but when I use datasets with a large resolution images it crashes while creating the scene with error message "Killed". 

`
$ sudo dmesg | grep -i killed
`  
  
`
[ 9251.115088] Out of memory: Killed process 33770 (gaussian_splatt) total-vm:48827652kB, anon-rss:29329872kB, file-rss:73216kB, shmem-rss:14080kB, UID:1000 pgtables:65480kB oom_score_adj:200
`

I'm running on a 4080 with 16gb vram.

I used the garden scene from MIP-Nerf360 https://jonbarron.info/mipnerf360/

It crashes in line 44 in camera.cu after the 120th to 140th camera.

**Comment by MrNeRF** [comment]
You can try to run with -r 2 or -r 4 witch will downscale the resolution.
I hope that helps.

**Comment by aml2007** [comment]
Yes, that works. Thank you
